# Generated by Django 4.2.2 on 2023-06-09 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_is_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
